name: usb_gadget
description: Expose standard or fully custom USB peripherals (gadgets) through a USB device controller (UDC) on Linux.
version: 0.3.0
homepage: https://github.com/GuillaumeMCK/usb-gadget

environment:
  sdk: ^3.11.0

dependencies:
  ffi: ^2.1.5
  meta: ^1.18.0
  using: ^1.0.5

dev_dependencies:
  ffigen: ^20.1.1
  leancode_lint: ^21.0.0
  lints: ^6.0.0
