// ignore_for_file: type=lint, unused_import, unused_field

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// FFI bindings for epoll and eventfd system calls
class Epoll {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  Epoll(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  Epoll.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int epoll_create1(int __flags) {
    return _epoll_create1(__flags);
  }

  late final _epoll_create1Ptr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>('epoll_create1');
  late final _epoll_create1 = _epoll_create1Ptr.asFunction<int Function(int)>();

  int epoll_ctl(
    int __epfd,
    int __op,
    int __fd,
    ffi.Pointer<epoll_event> __event,
  ) {
    return _epoll_ctl(__epfd, __op, __fd, __event);
  }

  late final _epoll_ctlPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Int, ffi.Int, ffi.Int, ffi.Pointer<epoll_event>)
        >
      >('epoll_ctl');
  late final _epoll_ctl = _epoll_ctlPtr
      .asFunction<int Function(int, int, int, ffi.Pointer<epoll_event>)>();

  int epoll_wait(
    int __epfd,
    ffi.Pointer<epoll_event> __events,
    int __maxevents,
    int __timeout,
  ) {
    return _epoll_wait(__epfd, __events, __maxevents, __timeout);
  }

  late final _epoll_waitPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Int, ffi.Pointer<epoll_event>, ffi.Int, ffi.Int)
        >
      >('epoll_wait');
  late final _epoll_wait = _epoll_waitPtr
      .asFunction<int Function(int, ffi.Pointer<epoll_event>, int, int)>();

  int eventfd(int __count, int __flags) {
    return _eventfd(__count, __flags);
  }

  late final _eventfdPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.UnsignedInt, ffi.Int)>>(
        'eventfd',
      );
  late final _eventfd = _eventfdPtr.asFunction<int Function(int, int)>();

  int eventfd_read(int __fd, ffi.Pointer<ffi.Uint64> __value) {
    return _eventfd_read(__fd, __value);
  }

  late final _eventfd_readPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Pointer<ffi.Uint64>)>
      >('eventfd_read');
  late final _eventfd_read = _eventfd_readPtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Uint64>)>();

  int eventfd_write(int __fd, int __value) {
    return _eventfd_write(__fd, __value);
  }

  late final _eventfd_writePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Uint64)>>(
        'eventfd_write',
      );
  late final _eventfd_write = _eventfd_writePtr
      .asFunction<int Function(int, int)>();
}

final class epoll_data extends ffi.Union {
  external ffi.Pointer<ffi.Void> ptr;

  @ffi.Int()
  external int fd;

  @ffi.Uint32()
  external int u32;

  @ffi.Uint64()
  external int u64;
}

final class epoll_event extends ffi.Struct {
  @ffi.Uint32()
  external int events;

  external epoll_data data;
}

const int EPOLL_CLOEXEC = 524288;

const int EPOLLIN = 1;

const int EPOLLPRI = 2;

const int EPOLLOUT = 4;

const int EPOLLRDNORM = 64;

const int EPOLLRDBAND = 128;

const int EPOLLWRNORM = 256;

const int EPOLLWRBAND = 512;

const int EPOLLMSG = 1024;

const int EPOLLERR = 8;

const int EPOLLHUP = 16;

const int EPOLLRDHUP = 8192;

const int EPOLLEXCLUSIVE = 268435456;

const int EPOLLWAKEUP = 536870912;

const int EPOLLONESHOT = 1073741824;

const int EPOLLET = 2147483648;

const int EPOLL_CTL_ADD = 1;

const int EPOLL_CTL_DEL = 2;

const int EPOLL_CTL_MOD = 3;

const int EPOLL_IOC_TYPE = 138;

const int EFD_SEMAPHORE = 1;

const int EFD_CLOEXEC = 524288;

const int EFD_NONBLOCK = 2048;
