// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_field
import 'dart:ffi' as ffi;

/// FFI bindings for epoll and eventfd system calls
class Epoll {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  Epoll(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  Epoll.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
      ) : _lookup = lookup;

  /// Creates a new epoll file descriptor.
  ///
  /// [flags] may be 0 or [EPOLL_CLOEXEC].
  int epoll_create1(int flags) {
    return _epoll_create1(flags);
  }

  late final _epoll_create1Ptr =
  _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>('epoll_create1');
  late final _epoll_create1 = _epoll_create1Ptr.asFunction<int Function(int)>();

  /// Adds, modifies, or removes entries in the interest list of [epfd].
  ///
  /// [op] is one of [EPOLL_CTL_ADD], [EPOLL_CTL_MOD], [EPOLL_CTL_DEL].
  int epoll_ctl(
      int epfd,
      int op,
      int fd,
      ffi.Pointer<epoll_event> event,
      ) {
    return _epoll_ctl(epfd, op, fd, event);
  }

  late final _epoll_ctlPtr =
  _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Int,
              ffi.Int,
              ffi.Int,
              ffi.Pointer<epoll_event>,
              )
      >
  >('epoll_ctl');
  late final _epoll_ctl = _epoll_ctlPtr
      .asFunction<int Function(int, int, int, ffi.Pointer<epoll_event>)>();

  /// Waits for events on [epfd], writing at most [maxevents] into [events].
  ///
  /// [timeout] in milliseconds; -1 means block indefinitely.
  /// Returns the number of ready file descriptors, 0 on timeout, -1 on error.
  int epoll_wait(
      int epfd,
      ffi.Pointer<epoll_event> events,
      int maxevents,
      int timeout,
      ) {
    return _epoll_wait(epfd, events, maxevents, timeout);
  }

  late final _epoll_waitPtr =
  _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Int,
              ffi.Pointer<epoll_event>,
              ffi.Int,
              ffi.Int,
              )
      >
  >('epoll_wait');
  late final _epoll_wait = _epoll_waitPtr
      .asFunction<int Function(int, ffi.Pointer<epoll_event>, int, int)>();

  /// Creates an eventfd object with the given initial [initval] and [flags].
  ///
  /// Returns a file descriptor. Use [EFD_SEMAPHORE] / [EFD_NONBLOCK] /
  /// [EFD_CLOEXEC] as flags.
  int eventfd(int initval, int flags) {
    return _eventfd(initval, flags);
  }

  late final _eventfdPtr =
  _lookup<ffi.NativeFunction<ffi.Int Function(ffi.UnsignedInt, ffi.Int)>>(
    'eventfd',
  );
  late final _eventfd = _eventfdPtr.asFunction<int Function(int, int)>();

  /// Reads the eventfd counter, blocking until it is non-zero.
  ///
  /// On success the counter is reset to 0 (or decremented by 1 if
  /// [EFD_SEMAPHORE] was set) and [value] is filled with the previous count.
  int eventfd_read(int fd, ffi.Pointer<ffi.Uint64> value) {
    return _eventfd_read(fd, value);
  }

  late final _eventfd_readPtr =
  _lookup<
      ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Pointer<ffi.Uint64>)>
  >('eventfd_read');
  late final _eventfd_read = _eventfd_readPtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Uint64>)>();

  /// Adds [value] to the eventfd counter, waking any blocked readers.
  int eventfd_write(int fd, int value) {
    return _eventfd_write(fd, value);
  }

  late final _eventfd_writePtr =
  _lookup<
      ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Uint64)>
  >('eventfd_write');
  late final _eventfd_write = _eventfd_writePtr
      .asFunction<int Function(int, int)>();
}

// ---------------------------------------------------------------------------
// epoll_event
// ---------------------------------------------------------------------------

/// The data carried by an epoll event — a C union; we expose [fd] and [u64].
final class epoll_data extends ffi.Union {
  external ffi.Pointer<ffi.Void> ptr;

  @ffi.Int()
  external int fd;

  @ffi.Uint32()
  external int u32;

  @ffi.Uint64()
  external int u64;
}

final class epoll_event extends ffi.Struct {
  @ffi.Uint32()
  external int events;

  external epoll_data data;
}

// ---------------------------------------------------------------------------
// Constants — epoll
// ---------------------------------------------------------------------------

/// Close-on-exec flag for [epoll_create1].
const int EPOLL_CLOEXEC = 524288; // O_CLOEXEC

const int EPOLL_CTL_ADD = 1;
const int EPOLL_CTL_DEL = 2;
const int EPOLL_CTL_MOD = 3;

/// Available for [epoll_event.events].
const int EPOLLIN = 0x001;
const int EPOLLPRI = 0x002;
const int EPOLLOUT = 0x004;
const int EPOLLERR = 0x008;
const int EPOLLHUP = 0x010;
const int EPOLLRDHUP = 0x2000;
const int EPOLLWAKEUP = 1 << 29;
const int EPOLLONESHOT = 1 << 30;
const int EPOLLET = 1 << 31;

// ---------------------------------------------------------------------------
// Constants — eventfd
// ---------------------------------------------------------------------------

const int EFD_SEMAPHORE = 1;
const int EFD_CLOEXEC = 524288; // O_CLOEXEC
const int EFD_NONBLOCK = 2048; // O_NONBLOCK