// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// FFI bindings for mount system calls
class Mount {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  Mount(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  Mount.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// Mount a filesystem.
  int mount(
    ffi.Pointer<ffi.Char> __special_file,
    ffi.Pointer<ffi.Char> __dir,
    ffi.Pointer<ffi.Char> __fstype,
    int __rwflag,
    ffi.Pointer<ffi.Void> __data,
  ) {
    return _mount(__special_file, __dir, __fstype, __rwflag, __data);
  }

  late final _mountPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.UnsignedLong,
            ffi.Pointer<ffi.Void>,
          )
        >
      >('mount');
  late final _mount = _mountPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Void>,
        )
      >();

  /// Unmount a filesystem.
  int umount(ffi.Pointer<ffi.Char> __special_file) {
    return _umount(__special_file);
  }

  late final _umountPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'umount',
      );
  late final _umount = _umountPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// Unmount a filesystem.  Force unmounting if FLAGS is set to MNT_FORCE.
  int umount2(ffi.Pointer<ffi.Char> __special_file, int __flags) {
    return _umount2(__special_file, __flags);
  }

  late final _umount2Ptr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Int)>
      >('umount2');
  late final _umount2 = _umount2Ptr
      .asFunction<int Function(ffi.Pointer<ffi.Char>, int)>();
}

const int MS_RDONLY = 1;

const int MS_NOSUID = 2;

const int MS_NODEV = 4;

const int MS_NOEXEC = 8;

const int MS_SYNCHRONOUS = 16;

const int MS_REMOUNT = 32;

const int MS_MANDLOCK = 64;

const int MS_DIRSYNC = 128;

const int MS_NOSYMFOLLOW = 256;

const int MS_NOATIME = 1024;

const int MS_NODIRATIME = 2048;

const int MS_BIND = 4096;

const int MS_MOVE = 8192;

const int MS_REC = 16384;

const int MS_VERBOSE = 32768;

const int MS_SILENT = 32768;

const int MS_POSIXACL = 65536;

const int MS_UNBINDABLE = 131072;

const int MS_PRIVATE = 262144;

const int MS_SLAVE = 524288;

const int MS_SHARED = 1048576;

const int MS_RELATIME = 2097152;

const int MS_KERNMOUNT = 4194304;

const int MS_I_VERSION = 8388608;

const int MS_STRICTATIME = 16777216;

const int MS_LAZYTIME = 33554432;

const int MS_SUBMOUNT = 67108864;

const int MS_NOREMOTELOCK = 134217728;

const int MS_NOSEC = 268435456;

const int MS_BORN = 536870912;

const int MS_ACTIVE = 1073741824;

const int MS_NOUSER = -2147483648;

const int MS_RMT_MASK = 41943121;

const int MS_MGC_VAL = 3236757504;

const int MS_MGC_MSK = 4294901760;

const int MNT_ID_REQ_SIZE_VER0 = 24;

const int MNT_ID_REQ_SIZE_VER1 = 32;

const int MNT_FORCE = 1;

const int MNT_DETACH = 2;

const int MNT_EXPIRE = 4;

const int UMOUNT_NOFOLLOW = 8;
