// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// FFI bindings for aio system calls
class Aio {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  Aio(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  Aio.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int io_setup(int maxevents, ffi.Pointer<ffi.Pointer<io_context>> ctxp) {
    return _io_setup(maxevents, ctxp);
  }

  late final _io_setupPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Int, ffi.Pointer<ffi.Pointer<io_context>>)
        >
      >('io_setup');
  late final _io_setup = _io_setupPtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Pointer<io_context>>)>();

  int io_destroy(ffi.Pointer<io_context> ctx) {
    return _io_destroy(ctx);
  }

  late final _io_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<io_context>)>>(
        'io_destroy',
      );
  late final _io_destroy = _io_destroyPtr
      .asFunction<int Function(ffi.Pointer<io_context>)>();

  int io_submit(
    ffi.Pointer<io_context> ctx,
    int nr,
    ffi.Pointer<ffi.Pointer<iocb>> ios,
  ) {
    return _io_submit(ctx, nr, ios);
  }

  late final _io_submitPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<io_context>,
            ffi.Long,
            ffi.Pointer<ffi.Pointer<iocb>>,
          )
        >
      >('io_submit');
  late final _io_submit = _io_submitPtr
      .asFunction<
        int Function(
          ffi.Pointer<io_context>,
          int,
          ffi.Pointer<ffi.Pointer<iocb>>,
        )
      >();

  int io_cancel(
    ffi.Pointer<io_context> ctx,
    ffi.Pointer<iocb> iocb$1,
    ffi.Pointer<io_event> evt,
  ) {
    return _io_cancel(ctx, iocb$1, evt);
  }

  late final _io_cancelPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<io_context>,
            ffi.Pointer<iocb>,
            ffi.Pointer<io_event>,
          )
        >
      >('io_cancel');
  late final _io_cancel = _io_cancelPtr
      .asFunction<
        int Function(
          ffi.Pointer<io_context>,
          ffi.Pointer<iocb>,
          ffi.Pointer<io_event>,
        )
      >();

  int io_getevents(
    ffi.Pointer<io_context> ctx,
    int min_nr,
    int nr,
    ffi.Pointer<io_event> events,
    ffi.Pointer<timespec> timeout,
  ) {
    return _io_getevents(ctx, min_nr, nr, events, timeout);
  }

  late final _io_geteventsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<io_context>,
            ffi.Long,
            ffi.Long,
            ffi.Pointer<io_event>,
            ffi.Pointer<timespec>,
          )
        >
      >('io_getevents');
  late final _io_getevents = _io_geteventsPtr
      .asFunction<
        int Function(
          ffi.Pointer<io_context>,
          int,
          int,
          ffi.Pointer<io_event>,
          ffi.Pointer<timespec>,
        )
      >();
}

final class timespec extends ffi.Struct {
  @ffi.Long()
  external int tv_sec;

  @ffi.Long()
  external int tv_nsec;
}

final class sockaddr extends ffi.Opaque {}

final class iovec extends ffi.Opaque {}

final class io_context extends ffi.Opaque {}

final class io_iocb_poll extends ffi.Struct {
  @ffi.Int()
  external int events;

  @ffi.Int()
  external int __pad1;
}

final class io_iocb_sockaddr extends ffi.Struct {
  external ffi.Pointer<sockaddr> addr;

  @ffi.UnsignedLong()
  external int len;
}

final class io_iocb_common extends ffi.Struct {
  external ffi.Pointer<ffi.Void> buf;

  @ffi.UnsignedLong()
  external int nbytes;

  @ffi.LongLong()
  external int offset;

  @ffi.LongLong()
  external int __pad3;

  @ffi.UnsignedInt()
  external int flags;

  @ffi.UnsignedInt()
  external int resfd;
}

final class io_iocb_vector extends ffi.Struct {
  external ffi.Pointer<iovec> vec;

  @ffi.UnsignedLong()
  external int nr;

  @ffi.LongLong()
  external int offset;
}

final class UnnamedUnion extends ffi.Union {
  external io_iocb_common c;

  external io_iocb_vector v;

  external io_iocb_poll poll;

  external io_iocb_sockaddr saddr;
}

final class iocb extends ffi.Struct {
  external ffi.Pointer<ffi.Void> data;

  @ffi.UnsignedInt()
  external int key;

  @ffi.UnsignedInt()
  external int aio_rw_flags;

  @ffi.Short()
  external int aio_lio_opcode;

  @ffi.Short()
  external int aio_reqprio;

  @ffi.Int()
  external int aio_fildes;

  external UnnamedUnion u;
}

final class io_event extends ffi.Struct {
  external ffi.Pointer<ffi.Void> data;

  external ffi.Pointer<iocb> obj;

  @ffi.UnsignedLong()
  external int res;

  @ffi.UnsignedLong()
  external int res2;
}
