// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// FFI bindings for ioctl system calls
class Ioctl {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  Ioctl(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  Ioctl.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int ioctl(int __fd, int __request) {
    return _ioctl(__fd, __request);
  }

  late final _ioctlPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.UnsignedLong)>>(
        'ioctl',
      );
  late final _ioctl = _ioctlPtr.asFunction<int Function(int, int)>();
}

const int FUNCTIONFS_FIFO_STATUS = 26369;

const int FUNCTIONFS_FIFO_FLUSH = 26370;

const int FUNCTIONFS_CLEAR_HALT = 26371;

const int FUNCTIONFS_INTERFACE_REVMAP = 26496;

const int FUNCTIONFS_ENDPOINT_REVMAP = 26497;

const int FUNCTIONFS_ENDPOINT_DESC = 2148099970;

const int FUNCTIONFS_DMABUF_ATTACH = 1074030467;

const int FUNCTIONFS_DMABUF_DETACH = 1074030468;

const int FUNCTIONFS_DMABUF_TRANSFER = 1074816901;
